export const BASE_URL_BACK = 'https://api.magiccollections.com.br'
export const BASE_URL_FRONT = 'http://localhost:3000'
export const BASE_URL_API_MAGIC = 'https://api.magicthegathering.io/v1/cards'
export const BASE_URL_PHOTO = 'https://api.magiccollections.com.br/images/resized'
export const BASE_URL_LOGIN = 'http://localhost:3000/login'